### ISSUE TITLE
Does calc_dm() relativize data before calculating bray-curtis?

### ISSUE THREAD

**Issue by aalexiev** [leffj/mctoolsr#31]
Just checking, but based on the source code I found for mctoolsr, I don't think calc_dm() currently relativizes the species matrix before calculating bray-curtis. I wanted to make sure I wasn't misreading the bit of code I found. Should we be calculating relative abundance via decostand before running calc_dm in this case?

Thanks,

Alex

**Comment by hhollandmoritz** [comment]
I think it's assumed that you have relativized it yourself first. In the
tutorial this happens during the single_rarefy step.

--
Hannah Holland-Moritz
Doctoral Candidate, Fierer Lab
EBIO Department
University of Colorado Boulder
she/her pronouns
hhollandmoritz@gmail.com
http://apipetteandanopenmind.wordpress.com/
<http://www.apipetteandanopenmind.wordpress.com>

**Comment by cliffbueno** [comment]
Hi Alex,
You are correct. If we look at the `calc_dm()` code here [https://github.com/leffj/mctoolsr/blob/master/R/dissimilarity-based.R](url), we see that it does not relativize the data. But Hannah is right, if you have rarefied your data, then they are already relativized. If not, then you can calculate relative abundance yourself. 
-Cliff
