### ISSUE TITLE
calc_pairwise_permanovas error#1

### ISSUE THREAD

**Issue by gafnialmog** [leffj/mctoolsr#35]
Error in combn(levels(comp_var), 2) : n < m

What does it mean?

**Comment by leffj** [comment]
Can you provide a reproducible example? Include the minimal code needed to reproduce the error.

**Comment by cliffbueno** [comment]
Hi @gafnialmog,

This error is likely caused by using a non-factor variable as your compare_header argument in calc_pairwise_permanovas.

I have reproduced the error by trying a numeric column instead of factor as my compare_header.
