### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by psinghuwa** [leffj/mctoolsr#38]
Hi I am trying to install this package in new version of Rstudio and getting error as memory.limit() has been discontinued any suggestion?

 devtools::install_github("leffj/mctoolsr")
Downloading GitHub repo leffj/mctoolsr@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                               
 2: CRAN packages only                
 3: None                              
 4: rlang    (1.1.2  -> 1.1.3 ) [CRAN]
 5: glue     (1.6.2  -> 1.7.0 ) [CRAN]
 6: cli      (3.6.1  -> 3.6.2 ) [CRAN]
 7: vctrs    (0.6.4  -> 0.6.5 ) [CRAN]
 8: stringi  (1.8.2  -> 1.8.3 ) [CRAN]
 9: Rcpp     (1.0.11 -> 1.0.12) [CRAN]
10: fansi    (1.0.5  -> 1.0.6 ) [CRAN]
11: Rhdf5lib (1.24.0 -> 1.24.1) [CRAN]
12: scales   (1.2.1  -> 1.3.0 ) [CRAN]
13: rhdf5    (2.46.0 -> 2.46.1) [CRAN]
14: jsonlite (1.8.7  -> 1.8.8 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:  
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\00113286\AppData\Local\Temp\RtmpaSPtIj\remotes4134403a5a4\leffj-mctoolsr-c7c9404/DESCRIPTION'
─  preparing 'mctoolsr': (540ms)
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory 'mctoolsr/vignettes'
─  building 'mctoolsr_0.1.1.9.tar.gz'
   
Warning message:
'memory.limit()' is no longer supported 
Error: could not find function "memory.limit"
Execution halted
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/AppData/Local/Temp/RtmpaSPtIj/file41345c48282f/mctoolsr_0.1.1.9.tar.gz’ had non-zero exit status

**Comment by cliffbueno** [comment]
Hi @psinghuwa, which version of R are you running?

**Comment by cliffbueno** [comment]
Closing due to lack of response. I suggest trying with a different version of R (maybe older version). I am running mctoolsr on R 4.2.3. Check out the RSwitch app for switching between R versions.
