### ISSUE TITLE
Calculation of OTU-level overlap

### ISSUE THREAD

**Issue by tobinhammer** [leffj/mctoolsr#9]
This could be useful in tracking sources. For example, to ask what percent of the OTUs found in a potential "sink" category (e.g., door handles), were present in a potential source category (e.g., hands)? -> "90% of the OTUs found on door handles were also present on hands"

It might be additionally helpful to filter by OTU relative abundance before the calculation, for the sink or source or both. -> "95% of the dominant OTUs (>2% relative abundance) on door handles ..."

**Comment by leffj** [comment]
OK, take a look at the new function, `calc_prop_taxa_from_sample_type()`. This should do what you want.

You could do the filtering by relative abundance you suggest using a filter_taxa... command beforehand.

**Comment by tobinhammer** [comment]
Looks great, thanks for implementing that!
